apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tt6zz3muz-nodejs
  janus-idp.io/tekton: tt6zz3muz-nodejs
  backstage.io/kubernetes-id: tt6zz3muz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tt6zz3muz-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
